version: '3'

services:
 flaskproj:
   restart: always
   build:
     context: .
     dockerfile: Dockerfile
   volumes: ["./flaskproj:/opt/flaskproj"]
   environment:
     PORT: "5000"
     FLASK_DEBUG: "true"
   ports:
     - "5000:8080"